// Auto-generated image paths from public/images/Frames
export const IMAGE_PATHS = 
[
  "/images/Frames/family frames 4x/family_13.png",
  "/images/Frames/travel export 4x/travel_04.png",
  "/images/Frames/food frames/1x/food_01.png",
  "/images/Frames/food frames/1x/food_06.png",
  "/images/Frames/us frames 4x/us_06.png",
  "/images/Frames/food frames/1x/food_02.png",
  "/images/Frames/food frames/1x/food_37.png",
  "/images/Frames/friends export 4x/friends_36.png",
  "/images/Frames/travel export 4x/travel_07.png",
  "/images/Frames/work export/work_49.png",
  "/images/Frames/work export/work_24.png",
  "/images/Frames/work export/work_11.png",
  "/images/Frames/work export/work_38.png",
  "/images/Frames/family frames 4x/family_34.png",
  "/images/Frames/work export/work_45.png",
  "/images/Frames/work export/work_31.png",
  "/images/Frames/travel export 4x/travel_11.png",
  "/images/Frames/friends export 4x/friends_40.png",
  "/images/Frames/friends export 4x/friends_44.png",
  "/images/Frames/work export/work_37.png",
  "/images/Frames/friends export 4x/friends_39.png",
  "/images/Frames/travel export 4x/travel_06.png",
  "/images/Frames/work export/work_10.png",
  "/images/Frames/family frames 4x/family_22.png",
  "/images/Frames/friends export 4x/friends_32.png",
  "/images/Frames/work export/work_20.png",
  "/images/Frames/food frames/1x/food_22.png",
  "/images/Frames/friends export 4x/friends_25.png",
  "/images/Frames/work export/work_09.png",
  "/images/Frames/travel export 4x/travel_33.png",
  "/images/Frames/family frames 4x/family_11.png",
  "/images/Frames/work export/work_30.png",
  "/images/Frames/work export/work_12.png",
  "/images/Frames/work export/work_08.png",
  "/images/Frames/food frames/1x/food_04.png",
  "/images/Frames/food frames/1x/food_14.png",
  "/images/Frames/family frames 4x/family_38.png",
  "/images/Frames/travel export 4x/travel_27.png",
  "/images/Frames/family frames 4x/family_33.png",
  "/images/Frames/food frames/1x/food_13.png",
  "/images/Frames/family frames 4x/family_27.png",
  "/images/Frames/food frames/1x/food_33.png",
  "/images/Frames/work export/work_15.png",
  "/images/Frames/travel export 4x/travel_49.png",
  "/images/Frames/food frames/1x/food_27.png",
  "/images/Frames/food frames/1x/food_15.png",
  "/images/Frames/work export/work_34.png",
  "/images/Frames/food frames/1x/food_26.png",
  "/images/Frames/work export/work_44.png",
  "/images/Frames/travel export 4x/travel_18.png",
  "/images/Frames/food frames/1x/food_03.png",
  "/images/Frames/us frames 4x/us_16.png",
  "/images/Frames/travel export 4x/travel_01.png",
  "/images/Frames/us frames 4x/us_33.png",
  "/images/Frames/family frames 4x/family_21.png",
  "/images/Frames/food frames/1x/food_07.png",
  "/images/Frames/work export/work_01.png",
  "/images/Frames/family frames 4x/family_14.png",
  "/images/Frames/family frames 4x/family_23.png",
  "/images/Frames/travel export 4x/travel_19.png",
  "/images/Frames/us frames 4x/us_27.png",
  "/images/Frames/family frames 4x/family_07.png",
  "/images/Frames/travel export 4x/travel_08.png",
  "/images/Frames/food frames/1x/food_23.png",
  "/images/Frames/travel export 4x/travel_50.png",
  "/images/Frames/food frames/1x/food_28.png",
  "/images/Frames/food frames/1x/food_16.png",
  "/images/Frames/family frames 4x/family_47.png",
  "/images/Frames/family frames 4x/family_05.png",
  "/images/Frames/friends export 4x/friends_49.png",
  "/images/Frames/family frames 4x/family_30.png",
  "/images/Frames/food frames/4x/food_06.png",
  "/images/Frames/family frames 4x/family_04.png",
  "/images/Frames/friends export 4x/friends_37.png",
  "/images/Frames/food frames/4x/food_36.png",
  "/images/Frames/travel export 4x/travel_26.png",
  "/images/Frames/us frames 4x/us_44.png",
  "/images/Frames/us frames 4x/us_15.png",
  "/images/Frames/travel export 4x/travel_23.png",
  "/images/Frames/food frames/1x/food_41.png",
  "/images/Frames/work export/work_22.png",
  "/images/Frames/us frames 4x/us_09.png",
  "/images/Frames/work export/work_33.png",
  "/images/Frames/us frames 4x/us_28.png",
  "/images/Frames/us frames 4x/us_50.png",
  "/images/Frames/food frames/1x/food_39.png",
  "/images/Frames/food frames/4x/food_25.png",
  "/images/Frames/work export/work_40.png",
  "/images/Frames/family frames 4x/family_17.png",
  "/images/Frames/family frames 4x/family_18.png",
  "/images/Frames/travel export 4x/travel_14.png",
  "/images/Frames/us frames 4x/us_20.png",
  "/images/Frames/family frames 4x/family_08.png",
  "/images/Frames/us frames 4x/us_31.png",
  "/images/Frames/travel export 4x/travel_05.png",
  "/images/Frames/food frames/4x/food_42.png",
  "/images/Frames/food frames/4x/food_49.png",
  "/images/Frames/work export/work_27.png",
  "/images/Frames/food frames/4x/food_08.png",
  "/images/Frames/food frames/1x/food_29.png",
  "/images/Frames/us frames 4x/us_08.png",
  "/images/Frames/friends export 4x/friends_34.png",
  "/images/Frames/us frames 4x/us_24.png",
  "/images/Frames/family frames 4x/family_32.png",
  "/images/Frames/family frames 4x/family_29.png",
  "/images/Frames/friends export 4x/friends_16.png",
  "/images/Frames/travel export 4x/travel_41.png",
  "/images/Frames/friends export 4x/friends_13.png",
  "/images/Frames/friends export 4x/friends_31.png",
  "/images/Frames/friends export 4x/friends_09.png",
  "/images/Frames/us frames 4x/us_35.png",
  "/images/Frames/friends export 4x/friends_10.png",
  "/images/Frames/travel export 4x/travel_15.png",
  "/images/Frames/us frames 4x/us_38.png",
  "/images/Frames/us frames 4x/us_48.png",
  "/images/Frames/us frames 4x/us_36.png",
  "/images/Frames/work export/work_48.png",
  "/images/Frames/food frames/1x/food_11.png",
  "/images/Frames/friends export 4x/friends_35.png",
  "/images/Frames/travel export 4x/travel_45.png",
  "/images/Frames/travel export 4x/travel_34.png",
  "/images/Frames/friends export 4x/friends_20.png",
  "/images/Frames/travel export 4x/travel_35.png",
  "/images/Frames/food frames/1x/food_12.png",
  "/images/Frames/food frames/1x/food_05.png",
  "/images/Frames/food frames/4x/food_35.png",
  "/images/Frames/us frames 4x/us_34.png",
  "/images/Frames/food frames/1x/food_49.png",
  "/images/Frames/family frames 4x/family_20.png",
  "/images/Frames/family frames 4x/family_03.png",
  "/images/Frames/food frames/1x/food_38.png",
  "/images/Frames/us frames 4x/us_40.png",
  "/images/Frames/travel export 4x/travel_42.png",
  "/images/Frames/food frames/1x/food_20.png",
  "/images/Frames/travel export 4x/travel_03.png",
  "/images/Frames/family frames 4x/family_28.png",
  "/images/Frames/friends export 4x/friends_26.png",
  "/images/Frames/food frames/4x/food_44.png",
  "/images/Frames/family frames 4x/family_31.png",
  "/images/Frames/food frames/4x/food_09.png",
  "/images/Frames/us frames 4x/us_49.png",
  "/images/Frames/food frames/1x/food_21.png",
  "/images/Frames/travel export 4x/travel_09.png",
  "/images/Frames/food frames/1x/food_32.png",
  "/images/Frames/food frames/4x/food_48.png",
  "/images/Frames/us frames 4x/us_47.png",
  "/images/Frames/family frames 4x/family_25.png",
  "/images/Frames/work export/work_13.png",
  "/images/Frames/work export/work_06.png",
  "/images/Frames/us frames 4x/us_29.png",
  "/images/Frames/work export/work_36.png",
  "/images/Frames/friends export 4x/friends_30.png",
  "/images/Frames/travel export 4x/travel_39.png",
  "/images/Frames/food frames/4x/food_14.png",
  "/images/Frames/work export/work_05.png",
  "/images/Frames/friends export 4x/friends_38.png",
  "/images/Frames/food frames/4x/food_20.png",
  "/images/Frames/friends export 4x/friends_41.png",
  "/images/Frames/friends export 4x/friends_24.png",
  "/images/Frames/work export/work_25.png",
  "/images/Frames/work export/work_18.png",
  "/images/Frames/food frames/4x/food_46.png",
  "/images/Frames/travel export 4x/travel_13.png",
  "/images/Frames/us frames 4x/us_12.png",
  "/images/Frames/work export/work_43.png",
  "/images/Frames/travel export 4x/travel_25.png",
  "/images/Frames/food frames/1x/food_35.png",
  "/images/Frames/food frames/1x/food_50.png",
  "/images/Frames/food frames/food frame reference.png",
  "/images/Frames/friends export 4x/friends_50.png",
  "/images/Frames/friends export 4x/friends_06.png",
  "/images/Frames/family frames 4x/family_46.png",
  "/images/Frames/friends export 4x/friends_48.png",
  "/images/Frames/friends export 4x/friends_45.png",
  "/images/Frames/us frames 4x/us_45.png",
  "/images/Frames/family frames 4x/family_42.png",
  "/images/Frames/us frames 4x/us_02.png",
  "/images/Frames/family frames 4x/family_24.png",
  "/images/Frames/food frames/4x/food_45.png",
  "/images/Frames/friends export 4x/friends_17.png",
  "/images/Frames/food frames/4x/food_43.png",
  "/images/Frames/friends export 4x/friends_02.png",
  "/images/Frames/food frames/1x/food_10.png",
  "/images/Frames/us frames 4x/us_22.png",
  "/images/Frames/food frames/1x/food_25.png",
  "/images/Frames/work export/work_28.png",
  "/images/Frames/work export/work_17.png",
  "/images/Frames/friends export 4x/friends_46.png",
  "/images/Frames/us frames 4x/us_32.png",
  "/images/Frames/food frames/4x/food_12.png",
  "/images/Frames/work export/work_16.png",
  "/images/Frames/work export/work_29.png",
  "/images/Frames/family frames 4x/family_50.png",
  "/images/Frames/food frames/1x/food_45.png",
  "/images/Frames/work export/work_32.png",
  "/images/Frames/food frames/1x/food_18.png",
  "/images/Frames/food frames/4x/food_02.png",
  "/images/Frames/friends export 4x/friends_04.png",
  "/images/Frames/food frames/4x/food_40.png",
  "/images/Frames/food frames/1x/food_42.png",
  "/images/Frames/travel export 4x/travel_17.png",
  "/images/Frames/work export/work_07.png",
  "/images/Frames/us frames 4x/us_05.png",
  "/images/Frames/family frames 4x/family_44.png",
  "/images/Frames/family frames 4x/family_41.png",
  "/images/Frames/friends export 4x/friends_43.png",
  "/images/Frames/food frames/1x/food_44.png",
  "/images/Frames/travel export 4x/travel_40.png",
  "/images/Frames/us frames 4x/us_07.png",
  "/images/Frames/us frames 4x/us_39.png",
  "/images/Frames/us frames 4x/us_14.png",
  "/images/Frames/travel export 4x/travel_38.png",
  "/images/Frames/travel export 4x/travel_43.png",
  "/images/Frames/food frames/4x/food_19.png",
  "/images/Frames/food frames/1x/food_43.png",
  "/images/Frames/friends export 4x/friends_21.png",
  "/images/Frames/food frames/1x/food_17.png",
  "/images/Frames/us frames 4x/us_37.png",
  "/images/Frames/friends export 4x/friends_27.png",
  "/images/Frames/family frames 4x/family_02.png",
  "/images/Frames/us frames 4x/us_21.png",
  "/images/Frames/food frames/4x/food_50.png",
  "/images/Frames/travel export 4x/travel_12.png",
  "/images/Frames/travel export 4x/travel_28.png",
  "/images/Frames/us frames 4x/us_19.png",
  "/images/Frames/friends export 4x/friends_01.png",
  "/images/Frames/travel export 4x/travel_29.png",
  "/images/Frames/work export/work_14.png",
  "/images/Frames/travel export 4x/travel_02.png",
  "/images/Frames/work export/work_23.png",
  "/images/Frames/family frames 4x/family_48.png",
  "/images/Frames/family frames 4x/family_49.png",
  "/images/Frames/family frames 4x/family_01.png",
  "/images/Frames/travel export 4x/travel_30.png",
  "/images/Frames/family frames 4x/family_16.png",
  "/images/Frames/food frames/4x/food_04.png",
  "/images/Frames/food frames/1x/food_19.png",
  "/images/Frames/work export/work_19.png",
  "/images/Frames/food frames/4x/food_10.png",
  "/images/Frames/travel export 4x/travel_36.png",
  "/images/Frames/us frames 4x/us_26.png",
  "/images/Frames/family frames 4x/family_26.png",
  "/images/Frames/work export/work_03.png",
  "/images/Frames/work export/work_26.png",
  "/images/Frames/food frames/4x/food_05.png",
  "/images/Frames/travel export 4x/travel_44.png",
  "/images/Frames/us frames 4x/us_03.png",
  "/images/Frames/us frames 4x/us_17.png",
  "/images/Frames/us frames 4x/us_25.png",
  "/images/Frames/us frames 4x/us_41.png",
  "/images/Frames/food frames/1x/food_34.png",
  "/images/Frames/family frames 4x/family_39.png",
  "/images/Frames/travel export 4x/travel_48.png",
  "/images/Frames/food frames/4x/food_37.png",
  "/images/Frames/friends export 4x/friends_28.png",
  "/images/Frames/friends export 4x/friends_29.png",
  "/images/Frames/us frames 4x/us_43.png",
  "/images/Frames/friends export 4x/friends_19.png",
  "/images/Frames/food frames/4x/food_34.png",
  "/images/Frames/food frames/4x/food_13.png",
  "/images/Frames/food frames/4x/food_18.png",
  "/images/Frames/food frames/4x/food_22.png",
  "/images/Frames/food frames/4x/food_33.png",
  "/images/Frames/family frames 4x/family_45.png",
  "/images/Frames/food frames/1x/food_08.png",
  "/images/Frames/friends export 4x/friends_33.png",
  "/images/Frames/travel export 4x/travel_47.png",
  "/images/Frames/us frames 4x/us_04.png",
  "/images/Frames/us frames 4x/us_18.png",
  "/images/Frames/travel export 4x/travel_20.png",
  "/images/Frames/work export/work_21.png",
  "/images/Frames/work export/work_42.png",
  "/images/Frames/family frames 4x/family_19.png",
  "/images/Frames/work export/work_39.png",
  "/images/Frames/travel export 4x/travel_46.png",
  "/images/Frames/food frames/1x/food_24.png",
  "/images/Frames/family frames 4x/family_15.png",
  "/images/Frames/food frames/1x/food_09.png",
  "/images/Frames/family frames 4x/family_43.png",
  "/images/Frames/food frames/1x/food_31.png",
  "/images/Frames/friends export 4x/friends_42.png",
  "/images/Frames/food frames/1x/food_30.png",
  "/images/Frames/friends export 4x/friends_47.png",
  "/images/Frames/travel export 4x/travel_32.png",
  "/images/Frames/travel export 4x/travel_10.png",
  "/images/Frames/food frames/1x/food_36.png",
  "/images/Frames/family frames 4x/family_36.png",
  "/images/Frames/family frames 4x/family_12.png",
  "/images/Frames/family frames 4x/family_06.png",
  "/images/Frames/family frames 4x/family_09.png",
  "/images/Frames/family frames 4x/family_10.png",
  "/images/Frames/family frames 4x/family_35.png",
  "/images/Frames/family frames 4x/family_37.png",
  "/images/Frames/family frames 4x/family_40.png",
  "/images/Frames/food frames/4x/food_38.png",
  "/images/Frames/us frames 4x/us_23.png",
  "/images/Frames/travel export 4x/travel_31.png",
  "/images/Frames/travel export 4x/travel_16.png",
  "/images/Frames/food frames/4x/food_41.png",
  "/images/Frames/food frames/4x/food_21.png",
  "/images/Frames/friends export 4x/friends_15.png",
  "/images/Frames/food frames/4x/food_01.png",
  "/images/Frames/food frames/4x/food_32.png",
  "/images/Frames/food frames/4x/food_03.png",
  "/images/Frames/friends export 4x/friends_12.png",
  "/images/Frames/food frames/1x/food_46.png",
  "/images/Frames/food frames/food frame 1.png",
  "/images/Frames/food frames/4x/food_31.png",
  "/images/Frames/travel export 4x/travel_22.png",
  "/images/Frames/food frames/4x/food_30.png",
  "/images/Frames/work export/work_02.png",
  "/images/Frames/food frames/4x/food_15.png",
  "/images/Frames/food frames/4x/food_29.png",
  "/images/Frames/food frames/4x/food_39.png",
  "/images/Frames/us frames 4x/us_01.png",
  "/images/Frames/travel export 4x/travel_21.png",
  "/images/Frames/friends export 4x/friends_11.png",
  "/images/Frames/travel export 4x/travel_37.png",
  "/images/Frames/food frames/1x/food_48.png",
  "/images/Frames/friends export 4x/friends_03.png",
  "/images/Frames/work export/work_47.png",
  "/images/Frames/us frames 4x/us_13.png",
  "/images/Frames/us frames 4x/us_42.png",
  "/images/Frames/friends export 4x/friends_22.png",
  "/images/Frames/us frames 4x/us_10.png",
  "/images/Frames/food frames/1x/food_47.png",
  "/images/Frames/us frames 4x/us_11.png",
  "/images/Frames/food frames/1x/food_40.png",
  "/images/Frames/work export/work_04.png",
  "/images/Frames/work export/work_35.png",
  "/images/Frames/friends export 4x/friends_18.png",
  "/images/Frames/food frames/4x/food_24.png",
  "/images/Frames/food frames/4x/food_47.png",
  "/images/Frames/work export/work_50.png",
  "/images/Frames/us frames 4x/us_46.png",
  "/images/Frames/friends export 4x/friends_08.png",
  "/images/Frames/work export/work_41.png",
  "/images/Frames/food frames/4x/food_26.png",
  "/images/Frames/us frames 4x/us_30.png",
  "/images/Frames/food frames/4x/food_27.png",
  "/images/Frames/food frames/4x/food_11.png",
  "/images/Frames/friends export 4x/friends_14.png",
  "/images/Frames/friends export 4x/friends_05.png",
  "/images/Frames/work export/work_46.png",
  "/images/Frames/travel export 4x/travel_24.png",
  "/images/Frames/friends export 4x/friends_23.png",
  "/images/Frames/food frames/4x/food_16.png",
  "/images/Frames/food frames/4x/food_28.png",
  "/images/Frames/food frames/4x/food_07.png",
  "/images/Frames/food frames/4x/food_23.png",
  "/images/Frames/friends export 4x/friends_07.png",
  "/images/Frames/food frames/4x/food_17.png"
]
;
